{% set name = "NREL-PySAM" %}
{% set version = environ.get('VERSION') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

requirements:
  build:
    - pip
    - python
  run:
    - python

build:
  script_env:
   - PYTHONVER
   - VERSION
   - DIST_DIR

about:
  home: https://nrel-pysam.readthedocs.io
  license: BSD 3-Clause
  license_family: BSD
  license_file:
  summary: National Renewable Energy Laboratory's System Advisor Model Python Wrapper
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - dguittet
